=== shade34321/IT_3203/l6p1.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT catalog (course+)>
<!ELEMENT course (department, course_name, course_number, instructor, course_type, time, room)>
<!ELEMENT department (#PCDATA)>
<!ELEMENT course_name (#PCDATA)>
<!ELEMENT course_number (#PCDATA)>
<!ELEMENT instructor (#PCDATA)>
<!ELEMENT course_type (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT room (#PCDATA)>

<!ATTLIST course_type lab (true|false) "false">
<!ATTLIST course_type lecture (true|false) "true">

=== shade34321/IT_3203/l6p2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE catalog SYSTEM "http://webdev.spsu.edu/~salabsa/l6p1.dtd">
<catalog>
	<course>
		<department>Information Technology </department>
		<course_name>Introduction to Web Development</course_name>
		<course_number>IT 3203</course_number>
		<instructor>Bob Brown </instructor>
		<course_type lab="false" lecture="true"> </course_type>
		<time>1800 </time>
		<room>J-266 </room>	
	</course>
	<course>
		<department>Information Technology </department>
		<course_name>Data Communication and Networks</course_name>
		<course_number>IT 4323</course_number>
		<instructor>Steve Prettryman </instructor>
		<course_type lab="true" lecture="false"> </course_type>
		<time>1500 </time>
		<room>J-265 </room>	
	</course>
	<course>
		<department>English </department>
		<course_name>American Literature Mid 1800's to Present</course_name>
		<course_number>Engl 2132</course_number>
		<instructor>Terry Carter </instructor>
		<course_type lab="false" lecture="true"> </course_type>
		<time>1200</time>
		<room>J-264</room>	
	</course>
</catalog>
